# Generated by Django 4.0.6 on 2022-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
            ],
        ),
    ]
